### ISSUE TITLE
estimate command requires an ar-keypair-path even with --with-sol flag

### ISSUE THREAD

**Issue by jameslin101** [CalebEverett/arloader#1]
$ arloader estimate "<GLOB>" --with-sol
error: The following required arguments were not provided:
    --ar-keypair-path <AR_KEYPAIR_PATH>

USAGE:
    arloader --ar-keypair-path <AR_KEYPAIR_PATH> --base-url <AR_BASE_URL>

For more information try --help

**Comment by CalebEverett** [comment]
Thanks for the feedback. I'll see about making the estimate command work without needing either wallet.

**Comment by CalebEverett** [comment]
https://github.com/CalebEverett/arloader/releases/tag/v0.1.36

**Comment by CalebEverett** [comment]
You can use sol now without an ar wallet https://github.com/CalebEverett/arloader/releases/tag/v0.1.38

**Comment by jameslin101** [comment]
awesome!
