### ISSUE TITLE
Bundles never being accepted

### ISSUE THREAD

**Issue by Jac0xb** [CalebEverett/arloader#10]
https://explorer.solana.com/address/9Em18kRiGNBA1Rrx8oNBnftKj8dcFXFYyDchXQcKSV5r

`arloader upload \*.mp4 --with-sol --sol-keypair-path ~/.config/solana/devnet.json --ar-default-keypair --bundle-size 50`

```
 bundle txid                                   items      KB  status       confirms
------------------------------------------------------------------------------------
 L4YIOSLxpHLEL8oFk13rmVIMYXvMGTujMtRM0EMUBu4       3   38912  NotFound            0
 qsnuTQrhqxOoHxhJu_4RVOs-8JgGcf6OQHN9aF14Nlc       4   46121  NotFound            0
 h5IM9BIsfKZtKAZou3VuK3w-seTZnHf9dYWrCN7GowA       4   47642  NotFound            0
 Maac9oFEM2eTjp2iqiawljIjfY7SRDfCHngVIEvNyk0       3   39039  NotFound            0
 ZHuvQK60Eza4lWoIhTKstArSdlXUlzlFZA2F008QMIs       3   32708  NotFound            0
 4l18ZbtydWyvkkAJiUaq02vJJlsbuueWrITyZC6anIo       4   45692  NotFound            0
 quu63L_f-MCulXqaYOEJVd-8zNwm8PbyJuOKo58fDkU       4   46956  NotFound            0
 2OC_xvDoLKkBkh0sLDIQGhaVeksCWkSX7sDoVt3ijec       4   44346  NotFound            0
 YSnLMv67I0vWwOHiYCY0uDI9Cq8OUJRSra18evFZ1Is       4   49219  NotFound            0
```

`arloader upload *.webp --with-sol --sol-keypair-path ~/.config/solana/devnet.json --ar-default-keypair --bundle-size 50`
 
```
 bundle txid                                   items      KB  status       confirms
------------------------------------------------------------------------------------
 RXp4t5Ex-nJ0GIwbxDS_FpSMrP9KuCpq_rZO7ErG-2I      33   25983  NotFound            0
```

Am I able to get my SOL back if a transaction is never taken by a miner?

**Comment by CalebEverett** [comment]
That is likely from reward not high enough. Try `--reward-multiplier 2`. I can send the sol back for the not found ones. Do you want to to post the full list here?

**Comment by Jac0xb** [comment]
> That is likely from reward not high enough. Try `--reward-multiplier 2`. I can send the sol back for the not found ones. Do you want to to post the full list here or is it just the tx above?

Its fine, it was only a few dollars as a test. It seems odd that you have to use a multiplier.

**Comment by CalebEverett** [comment]
The [arweave api](https://docs.arweave.org/developers/server/http-api#get-transaction-price) returns the minimum price. The actual price required for miners to accept a transaction is variable, hence the multiplier concept. You can run a test like you did to see whether miners will accept the minimum at the time you are uploading and if not increase from there. It is also possible to have tx rejected for too high of a reward. It seems like a multiplier of 2 or 3 is usually sufficient.

**Comment by easeev** [comment]
I have the same issue for a single 6MB file. Tried all multipliers from 2 to 10, always getting `NotFound`
