### ISSUE TITLE
README errors

### ISSUE THREAD

**Issue by samuelvanderwaal** [CalebEverett/arloader#11]
From the README:

> If you are creating your NFTs with the Metaplex Candy Machine, you can create a json file with **links it** that you can copy and paste into your candy machine config by running the command below. <FILE_PATHS> can match **your** either your asset or metadata files.

There are a few grammatical errors and typos highlighted in bold, but more importantly: is this actually correct, or does this command require specifying the file paths for the metadata JSON files? If I specify `assets/*.png` I get `Error: IOError(Error { kind: InvalidData, message: "stream did not contain valid UTF-8" })`. I would expect this command to only operate on `assets/*.json` and that does indeed work.

**Comment by CalebEverett** [comment]
I'll get that cleaned up, you are correct - you do have to specify json file paths. I'll see if I can handle the errors better as well.
