### ISSUE TITLE
Crash happen when file reach to certain size

### ISSUE THREAD

**Issue by leozc** [CalebEverett/arloader#13]
When media file size larger 10MB, it crashed
arloader-0.1.55/src/commands.rs:743:26

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /Users/leozc/.cargo/registry/src/github.com-1ecc6299db9ec823/arloader-0.1.55/src/commands.rs:743:26
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: arloader::commands::command_upload_nfts::{{closure}}
   4: arloader::main::{{closure}}
   5: arloader::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

```rust
    let log_dir = if let Some(log_dir) = log_dir {
        log_dir
    } else {
        let parent_dir = path_chunks[0].0[0].parent().unwrap();
        arweave.create_log_dir(parent_dir).await?
    };
```

**Comment by CalebEverett** [comment]
Try increasing the bundle size to be bigger than your file size.
`--bundle-size 100` will increase it to 100mb.

**Comment by leozc** [comment]
That works - may make this become a more helpful error instead of a panic :)

Thanks!

**Comment by CalebEverett** [comment]
Will do - this actually came up once before as well. I think a bigger default bundle size would be better too. I'm not noticing much, if any, difference in upload speed between the `tx/` endpoint used if 10MB or less and the `chunk/` endpoint used if greater than that.
