### ISSUE TITLE
Error doesn't implement Send

### ISSUE THREAD

**Issue by ozgrakkurt** [CalebEverett/arloader#14]
this makes it very hard to use the Arweave since the errors it returns are !Send and that makes the Futures themselves !Send which makes running them in tokio not possible without LocalSet

**Comment by CalebEverett** [comment]
Can you give me an example of where this happens and the error message so I can try to track down and fix?

**Comment by ozgrakkurt** [comment]
there is no specific message just the future that calling `Arweave::get_price_terms` produces doesn't implement Send so we can't tokio::spawn it.
![image](https://user-images.githubusercontent.com/91746947/154134743-856f7ef4-4a15-4cc3-bf38-6092de52946b.png)

This is because the Error type doesn't implement Send

**Comment by CalebEverett** [comment]
Ok, I'll see if I can implement it - thanks.

**Comment by CalebEverett** [comment]
Let me know if [this](https://github.com/CalebEverett/arloader/blob/master/examples/error_send.rs) works. Master has the update and 1.57 should be on crates.io in 15 minutes or so.

**Comment by ozgrakkurt** [comment]
thank you it works!
