### ISSUE TITLE
Getting StatusCodeNotOk errors after trying to upload with SOL

### ISSUE THREAD

**Issue by murki** [CalebEverett/arloader#18]
Hi, this is my first time using your tool and I've been having issues all day trying to upload a single png/json pair. The operation fails but the SOL **_do get deducted from my wallet_** each time.

The same issues happen both when running `upload` or `upload-nfts`. This is what I'm doing (I'm using `mainnet-beta`):

`arloader upload assets/0.png --sol-keypair-path ~/.config/solana/my_wallet_keypair.json --with-sol --ar-default-keypair`
output:
```
Uploading 1 files with 93 KB of data in 1 bundle transactions...

StatusCodeNotOk

Uploaded 0 KB in 0 files in 0 bundle transaction(s). Run `arloader update-status assets/arloader_2Ot4PVp1jrA` to update statuses.
```
or
`arloader upload-nfts assets/*.png --with-sol --sol-keypair-path ~/.config/solana/my_wallet_keypair.json --ar-default-keypair`
output:
```
Uploading assets...

Uploading 1 files with 93 KB of data in 1 bundle transactions...

Retrying Solana transaction (1 of 10)...
StatusCodeNotOk

Uploaded 0 KB in 0 files in 0 bundle transaction(s). Run `arloader update-status assets/arloader_nk2gGXUQ7C8/assets/` to update statuses.

Uploading manifest for images...

No bundle statuses found in assets/arloader_nk2gGXUQ7C8/assets/
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/mjuarezlopez/.cargo/registry/src/github.com-1ecc6299db9ec823/arloader-0.1.60/src/commands.rs:802:6
```

Both operations create empty `arloader_<RANDOM_CHARS>` folders.

I tried using `--reward-multiplier` of 2 and 3 without luck. I also tried using the `--no-bundle` option with `upload` command but that doesn't seem to work at all.

**Comment by CalebEverett** [comment]
Hi, sorry about that. I'm trying to fix it now. Something changed in the gateway in the last day or so as arweave was implementing solutions to some problems it was having. I can let you know as soon as it is fixed. Sorry about the sol tx - refunding is manual right now, but if you send me the list of transactions I can send it back to you.

**Comment by CalebEverett** [comment]
Hi @murki I tracked this down. Master branch has the change - new release should be available on github and crates.io shortly. I can also send you some ar if you want to retry those transactions with ar instead of sol.

**Comment by murki** [comment]
Hi @CalebEverett thanks for the quick follow up. I sent you a friend request in Discord so I can send you the tx list. I'll give the update a try later today and let you know how it goes.

**Comment by murki** [comment]
Fixed by https://github.com/CalebEverett/arloader/commit/c2ebfa40ae022c95cf155ab98b3a3583c9db8dd9

**Comment by unimintco** [comment]
I'm using `arloader 0.1.62` on a Mac (binary downloaded from GH) and I get the same error. StatusNotOk and empty folders while sol gets deducted.

**Comment by CalebEverett** [comment]
I can refund the sol or send you some ar. StarusNotOk indicates an Arweave
or gateway issue, unfortunately.

**Comment by unimintco** [comment]
Don't worry about it, it's a pretty low amount (about 4 minimal transactions).
Then I guess we just wait?

**Comment by CalebEverett** [comment]
yes, but let me try on my end here and send me your ar wallet address so I
can send you some ar to keep trying with. If you keep trying with ar and
the tx don't go through it won't get deducted.
