### ISSUE TITLE
Bundlr support

### ISSUE THREAD

**Issue by joshbenaron** [CalebEverett/arloader#2]
Hey,

It would be great to provide a Bundlr integration meaning peoples bundles are guaranteed to get on chain. AR and SOL are already supported.

**Comment by CalebEverett** [comment]
Will do

**Comment by joshbenaron** [comment]
Yep. SOL is a lot friendlier in that manner. 

FYI we lowered the required confirmations on an AR transfer to 20.

If you need any support on the integration. Feel free to message me on Discord.

**Comment by CalebEverett** [comment]
What's the pricing?

**Comment by CalebEverett** [comment]
I was going to start on bundlr. I looked through your js client and it seems I need to:

1. Provide a way to fund a bundrl account - can this be done with any of the supported currencies?
2. Post data items - upload folder is sequence of data item posts with logging and manifest
3. Withdraw bundlr funds

**Comment by CalebEverett** [comment]
It looks like there is now a rust client for the bundlr network so closing this.
