### ISSUE TITLE
Trying to upload png/json 

### ISSUE THREAD

**Issue by ryansorr1** [CalebEverett/arloader#20]
Hi, 

Any Ideas what is going on here?

$ ./arloader upload-nfts inc/a/*.* --with-sol --sol-keypair-path wallet.json --ar-default-keypair

Uploading assets...

Uploading 598 files with 249510 KB of data in 3 bundle transactions...

 bundle txid                                   items      KB  status       confirms
------------------------------------------------------------------------------------
 uYpDF2_4DvBywQu2geqXeut4c7C4yMjiC7gQ-UhaZYk     239   98271  Submitted           0
Retrying Solana transaction (1 of 10)...
 TOZyZxnOGyra5LPhlEcCO1UgS7sXMnFdC9JrQTxPIyk     236   99834  Submitted           0
Retrying Solana transaction (1 of 10)...
 klFh_4YuuKYDphaHmvIEUTcB6K8ErenJfL9JwUduDb0     123   51404  Submitted           0

Uploaded 249510 KB in 598 files in 3 bundle transaction(s). Run `arloader update-status inc/a/arloader_Bhd-BmCczr0/assets/` to update statuses.

Uploading manifest for images...

Uploaded manifest for 598 files and wrote to inc/a/arloader_Bhd-BmCczr0/assets/manifest_Lgp1zj-QYDn9yaXKsiaxpJAOkTdrfXETTYn6KaCGG0Q.json.

Run `arloader get-status Lgp1zj-QYDn9yaXKsiaxpJAOkTdrfXETTYn6KaCGG0Q` to confirm manifest transaction.

Updating metadata with links from manifest...

Error: SerdeJson(Error("EOF while parsing a value", line: 1, column: 0))

**Comment by CalebEverett** [comment]
maybe the metadata file has an unexpected format - can you post a sample here?

**Comment by ryansorr1** [comment]
it works if I only do one, it is a problem when I do large numbers,  ALso I just need to update the description. I don't really need to reupload the images.  Can I just upload *.json and get the format I need for metaboss?



{
    "name": "Citizen #437",
    "symbol": "",
    "description": "Citizens",
    "seller_fee_basis_points": 700,
    "image": "https://arweave.net/mhiN8mYYiaanTBLx6QqJtbKh9RIr8iHlZce_05IdD5hg",
    "external_url": "https://xxxxxxxx.com/",
    "animation_url": "",
    "collection": {
        "name": "SCUM Citizens",
        "family": "SCUM"
    },
    "properties": {
        "files": [
            {
                "uri": "https://www.arweave.net/_BwnmYPFo6q0mhNkjs_HmmPebLpgUUBKw6rOvzfoSdI?ext=png",
                "type": "image/png"
            },
            {
                "uri": "https://arweave.net/mhiN8mYYiaanTBL6QqJtbKh9RIr8iHlZce_05IdD5hg",
                "type": "image/png"
            }
        ],
        "category": "image",
        "creators": [
            {
                "address": "mhiN8mYYiaanTBL6QqJtbKh9RIr8iHlZce_05IdD5hg",
                "share": 100
            }
        ]
    },
    "attributes": [
        {
            "trait_type": "Background",
            "value": "White"
        },
        {
            "trait_type": "Body",
            "value": "Purple"
        },
        {
            "trait_type": "Side",
            "value": "Jetpack Green"
        },
        {
            "trait_type": "Face",
            "value": "Cigar"
        },
        {
            "trait_type": "Eyes",
            "value": "Glasses Red"
        },
        {
            "trait_type": "Head",
            "value": "None"
        }
    ]
}

**Comment by CalebEverett** [comment]
Yes

**Comment by ryansorr1** [comment]
I have tried several times and I it always seems to fail, whether its the above error, solana transaction error or Not found error.  I have tried setting the reward multiplier to max 3.0. 

If I just upload the json files I get no error but then nothing gets confirmed always just says NotFound.  So figured it needed the png files too.

Lost

**Comment by CalebEverett** [comment]
it looks like a bunch of them worked https://arweave.net/12DFCfPSjOSCvtG31eMtZLRsoj3Sad-2vxQmh9zp4xc.

I can jump on discord chat with you at 3pm pacific.

**Comment by CalebEverett** [comment]
The gateway has been struggling of late, so sometimes the responses are delayed.

**Comment by CalebEverett** [comment]
Let me know when is good.

**Comment by ryansorr1** [comment]
for help? any time?

**Comment by CalebEverett** [comment]
Ok, can you dm me on discord at Caleb#9071
