### ISSUE TITLE
Constant issues with uploading nft set - StatusCodeNotOk

### ISSUE THREAD

**Issue by oliexe** [CalebEverett/arloader#22]
Using upload-nft results in StatusCodeNotOk. 

AR tokens get deducted, adding a reward multiplier does not work.
Resulting bundle is crrupted and fails verification.

Any idea what can help ?

I am using the latest build to this date.

**Comment by CalebEverett** [comment]
Hi, what version are you using?

**Comment by CalebEverett** [comment]
Hi @oliexe , the chunk endpoint changed over the last couple of days. I've removed the trailing slash and it is working again. Let me know if you need any other help.

**Comment by ngundotra** [comment]
++ having same issue w 0.1.62

**Comment by CalebEverett** [comment]
@ngundotra working on a fix - try this in the mean time https://github.com/CalebEverett/arloader/issues/24

**Comment by CalebEverett** [comment]
@ngundotra this issue seems to have resolved itself. I'm able to upload bundles with as many as 4k items in them successfully. Can you try on your send and see if you are finding the same thing? It may have been a network issue.

**Comment by ngundotra** [comment]
Yup, fixed itself. Love this tool!!! Thank you for responsiveness as well
