### ISSUE TITLE
Rust nightly toolchain

### ISSUE THREAD

**Issue by iupii** [CalebEverett/arloader#27]
As I can see there is only on feature from nightly — #![feature(derive_default_enum)], to derive default trait for status.
But with that it's not possible to use this crate as lib in stable toolchain.

**Comment by CalebEverett** [comment]
Hi, I'll take a look and see why I had that in there and if it is possible to remove.

**Comment by CalebEverett** [comment]
It looks like this feature will be supported very soon. I'll keep track of this a change to stable toolchain as soon as it lands.

https://github.com/rust-lang/rust/issues/87517#issuecomment-1090848732

**Comment by CalebEverett** [comment]
That was only used in one place. I changed it out and published a new release that works with the stable tool chain. https://github.com/CalebEverett/arloader/releases/tag/v0.1.63
