### ISSUE TITLE
error: Invalid value for '<FILE_PATHS>...': Path does not exist.

### ISSUE THREAD

**Issue by adityamatt** [CalebEverett/arloader#29]
![image](https://user-images.githubusercontent.com/33998232/169663692-77083236-e4ce-4429-a431-4ca617bbe63a.png)

Its not recognizing the regex in path which based on documentation should work.

There are json files in the current folder.

**Comment by CalebEverett** [comment]
Sorry, it doesn't do windows very well. Can you use wsl2?

**Comment by adityamatt** [comment]
Thanks for replying.

I switched to [arweave](https://www.npmjs.com/package/arweave#get-an-address-balance) to upload programatically with node

Maybe this can be a future improvement if this project is being maintained
