### ISSUE TITLE
funding transactions with SOL - upload not completed - SOL deducted 

### ISSUE THREAD

**Issue by tech-33** [CalebEverett/arloader#35]
when using arloader upload feature with solana as payment method I am getting error StatusCodeNotOk - File is never uploaded to arweave - the transaction is rebroadcasted and fails up to 10 times per try. The funds are deducted from solana wallet the same amount of times as it retries to resend - I have about 15 transactions that have deducted SOL from the wallet but no data uploaded to arweave.

**Comment by CalebEverett** [comment]
Hi, sorry about that. If you send me your sol.addtess, I can refund.

**Comment by tech-33** [comment]
SOL was refunded - will update and test arloader soon - thanks for the speedily reply !
