### ISSUE TITLE
Incorrect metadata Files Array format

### ISSUE THREAD

**Issue by samuelvanderwaal** [CalebEverett/arloader#9]
In `lib.rs` [on line 1629](https://github.com/CalebEverett/arloader/blob/7339ccc0ea736acb404eeb17a46fe473553e55ae/src/lib.rs#L1629) arloader replaces the files array with String values instead of the proper File Attribute object with "uri" and "type" fields. 

Like this:
![Selection_574](https://user-images.githubusercontent.com/1684605/149121165-eef2d8b5-e489-4627-b8d2-fff5e0c43512.png)

when the files array should look like this:

![Selection_575](https://user-images.githubusercontent.com/1684605/149121231-56ba1d4b-5b92-463d-a980-28be806442c9.png)

See the [Metaplex Token Metadata Standard](https://docs.metaplex.com/token-metadata/v1.0.0/nft-standard) for full details of the correct format.

**Comment by CalebEverett** [comment]
fixing now

**Comment by CalebEverett** [comment]
[v0.1.53](https://github.com/CalebEverett/arloader/blob/master/CHANGELOG.md#v0153-2022-01-12) fixes this. Also adds functionality to accommodate NFTs with multiple asset files (i.e., an image and a video).
